import Pkg
Pkg.add("LinearAlgebra")
Pkg.add("SIMD")
Pkg.add("CUDA")
Pkg.add("StaticArrays")
Pkg.add("InteractiveUtils")
Pkg.add("LLVM")
Pkg.add("GPUCompiler")
Pkg.add("FileIO")
Pkg.add("Colors")
Pkg.add("ImageTransformations")
Pkg.add("MLDatasets")
